name: Publish

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Test
        run: ./gradlew test
        env:
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}

      - name: Publish
        run: ./gradlew build
      - uses: actions/upload-artifact@v4.3.6
        name: build
        path: build/libs
        
